version: "3.7"
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
    ports:
      - "8094:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: library/mysql:8.0.20
    ports:
      - "3306:3306" #si le cambia el puerto se debe que configurar que apunte al puerto para que se pueda conectar me refiero al php
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./resources/docker/config/my.cfg:/etc/mysql/conf.d/config-file.cnf"
      - "./resources/migrations/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql"
